/**
 * Every user-facing string in Wadheek. Re-localize the app by editing this file.
 */
export const COPY = {
  app: {
    name: "Wadheek",
    tagline: "Edit video entirely in your browser. Nothing ever leaves your device.",
    privacyNote: "100% local — no uploads, no accounts, no tracking.",
  },
  nav: {
    projects: "Projects",
    settings: "Settings",
    editor: "Editor",
    back: "Back",
  },
  theme: {
    light: "Light",
    dark: "Dark",
    system: "System",
    toggleLabel: "Color theme",
  },
  dashboard: {
    title: "Your projects",
    subtitle: "Everything is stored privately in this browser.",
    newProject: "New project",
    emptyTitle: "No projects yet",
    emptyBody: "Create your first project to start editing. Projects, media and exports are stored locally in your browser.",
    emptyCta: "Create a project",
    importProject: "Import project",
    open: "Open",
    rename: "Rename",
    duplicate: "Duplicate",
    delete: "Delete",
    export: "Export file",
    deleteConfirmTitle: "Delete this project?",
    deleteConfirmBody: "The project and its timeline will be permanently removed from this browser. Imported media shared with other projects is kept.",
    lastEdited: "Edited",
    searchPlaceholder: "Search projects",
  },
  newProject: {
    title: "New project",
    description: "Pick a name and canvas. You can change everything later.",
    nameLabel: "Project name",
    namePlaceholder: "Untitled project",
    aspectLabel: "Canvas",
    fpsLabel: "Frame rate",
    create: "Create project",
  },
  editor: {
    saved: "Saved",
    saving: "Saving",
    unsaved: "Unsaved changes",
    export: "Export",
    media: "Media",
    inspector: "Inspector",
    timelineLabel: "Timeline editor",
    previewLabel: "Program monitor",
    addTrack: "Add track",
    emptyTimelineTitle: "Your timeline is empty",
    emptyTimelineBody: "Import media on the left, then drag clips here — or press the button below.",
    emptyTimelineCta: "Import media",
    dropHint: "Drop files to import",
    zoomIn: "Zoom in",
    zoomOut: "Zoom out",
    zoomFit: "Fit timeline",
    snap: "Magnetic snapping",
    play: "Play",
    pause: "Pause",
    stop: "Stop",
    goToStart: "Go to start",
    goToEnd: "Go to end",
    prevFrame: "Previous frame",
    nextFrame: "Next frame",
    loop: "Loop playback",
    setIn: "Mark in",
    setOut: "Mark out",
    clearInOut: "Clear in/out",
    addMarker: "Add marker",
    split: "Split at playhead",
    delete: "Delete",
    rippleDelete: "Ripple delete",
    duplicate: "Duplicate",
    copy: "Copy",
    paste: "Paste",
    undo: "Undo",
    redo: "Redo",
    mute: "Mute",
    solo: "Solo",
    lock: "Lock",
    hide: "Hide",
    renameTrack: "Rename track",
    deleteTrack: "Delete track",
    shortcuts: "Keyboard shortcuts",
    commandPalette: "Command palette",
    fitPreview: "Fit",
  },
  mediaLibrary: {
    title: "Media",
    importCta: "Import media",
    empty: "No media yet",
    emptyBody: "Import video, audio or images. Files are stored locally and never uploaded.",
    dropHere: "Drop files anywhere to import",
    addToTimeline: "Add to timeline",
    remove: "Remove from library",
    removeConfirmTitle: "Remove this media?",
    removeConfirmBody: "Clips that use this media will also be removed from the timeline.",
    importing: "Importing",
    probing: "Reading metadata",
  },
  inspector: {
    empty: "Nothing selected",
    emptyBody: "Select a clip in the timeline to edit its properties.",
    multi: "clips selected",
    transform: "Transform",
    position: "Position",
    scale: "Scale",
    rotation: "Rotation",
    opacity: "Opacity",
    blendMode: "Blend mode",
    crop: "Crop",
    speed: "Speed",
    preservePitch: "Preserve audio pitch",
    filters: "Color & effects",
    presets: "Looks",
    reset: "Reset",
    resetAll: "Reset all",
    text: "Text",
    content: "Content",
    font: "Font",
    size: "Size",
    weight: "Weight",
    alignment: "Alignment",
    color: "Color",
    stroke: "Stroke",
    shadow: "Shadow",
    background: "Background",
    animationIn: "Animate in",
    animationOut: "Animate out",
    audio: "Audio",
    volume: "Volume",
    pan: "Pan",
    fadeIn: "Fade in",
    fadeOut: "Fade out",
    muteClip: "Mute clip",
    transitions: "Transitions",
    transitionIn: "Transition in",
    transitionOut: "Transition out",
    duration: "Duration",
    timing: "Timing",
    start: "Start",
    clipName: "Label",
  },
  export: {
    title: "Export video",
    description: "Rendered locally in your browser using the same compositor as the preview.",
    fileName: "File name",
    format: "Format",
    resolution: "Resolution",
    frameRate: "Frame rate",
    quality: "Quality",
    bitrate: "Bitrate",
    range: "Range",
    rangeAll: "Entire timeline",
    rangeInOut: "In/Out range",
    start: "Start export",
    cancel: "Cancel",
    rendering: "Rendering",
    frame: "Frame",
    eta: "Est. remaining",
    done: "Export complete",
    doneBody: "Your video has been downloaded.",
    failed: "Export failed",
    canceled: "Export canceled",
    emptyTimeline: "Add clips to the timeline before exporting.",
    ffmpegUnavailable: "MP4 (ffmpeg.wasm) is not installed in /public/ffmpeg — falling back is documented in the README. WebM export works out of the box.",
  },
  settings: {
    title: "Settings",
    appearance: "Appearance",
    appearanceBody: "Choose how Wadheek looks. System follows your OS preference.",
    playback: "Editing",
    storage: "Storage",
    storageBody: "Wadheek stores projects and media in this browser (IndexedDB + Origin Private File System).",
    usage: "Estimated usage",
    clear: "Clear all local data",
    clearConfirmTitle: "Delete everything?",
    clearConfirmBody: "All projects, imported media and exports stored in this browser will be permanently deleted.",
    cleared: "All local data cleared",
    about: "About",
    snapDefault: "Enable snapping by default",
    autosave: "Autosave",
    autosaveBody: "Projects save automatically a moment after every change.",
  },
  toasts: {
    projectCreated: "Project created",
    projectRenamed: "Project renamed",
    projectDuplicated: "Project duplicated",
    projectDeleted: "Project deleted",
    projectExported: "Project file exported",
    projectImported: "Project imported",
    mediaImported: (n: number) => `${n} file${n === 1 ? "" : "s"} imported`,
    mediaRemoved: "Media removed",
    mediaImportFailed: "Some files could not be imported",
    clipSplit: "Clip split",
    clipsDeleted: (n: number) => `${n} clip${n === 1 ? "" : "s"} removed`,
    clipsCopied: (n: number) => `${n} clip${n === 1 ? "" : "s"} copied`,
    clipsPasted: (n: number) => `${n} clip${n === 1 ? "" : "s"} pasted`,
    trackAdded: "Track added",
    trackDeleted: "Track deleted",
    markerAdded: "Marker added",
    nothingToUndo: "Nothing to undo",
    nothingToRedo: "Nothing to redo",
    unsupportedFile: (name: string) => `Unsupported file: ${name}`,
    fileTooLarge: (name: string) => `File too large: ${name}`,
  },
  notFound: {
    title: "Page not found",
    body: "The page you are looking for does not exist or the project was deleted.",
    cta: "Back to projects",
  },
  confirm: {
    cancel: "Cancel",
    confirm: "Confirm",
    delete: "Delete",
  },
  dialogs: {
    ok: "OK",
    importIssuesTitle: "Some files could not be imported",
    importIssuesIntro: "The following files were skipped:",
    importUnsupported: (name: string) => `${name} — unsupported format`,
    importTooLarge: (name: string) => `${name} — exceeds the size limit`,
    importReadError: (name: string) => `${name} — could not be read`,
    exportCompleteTitle: "Export complete",
    exportCompleteBody: (file: string) =>
      `${file} was rendered locally and downloaded to your device.`,
    exportFailedTitle: "Export failed",
    exportFailedBody: "The render could not be completed. Try a lower resolution or a different format.",
    exportCanceledTitle: "Export canceled",
    exportCanceledBody: "The render was stopped. No file was saved.",
    exportEmptyTitle: "Nothing to export",
    mp4FallbackTitle: "MP4 encoder not available",
    addToTimelineFailedTitle: "Couldn't add to timeline",
    addToTimelineFailedBody:
      "No compatible unlocked track was found for this media. Unlock a track or add a new one, then try again.",
    deleteTrackTitle: "Delete this track?",
    deleteTrackBody: (name: string, clips: number) =>
      clips > 0
        ? `"${name}" contains ${clips} clip${clips === 1 ? "" : "s"}. Deleting the track removes them from the timeline. You can undo this.`
        : `"${name}" will be removed from the timeline. You can undo this.`,
    projectImportFailedTitle: "Project import failed",
    projectExportFailedTitle: "Project export failed",
    genericErrorBody: "Something went wrong. Please try again.",
  },
  a11y: {
    timeline: "Timeline. Use arrow keys to move the playhead, space to play or pause.",
    playhead: "Playhead",
    announcements: "Editor announcements",
  },
} as const;
