/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as NotFoundRouteImport } from "./routes/not-found"
import { Route as SettingsRouteImport } from "./routes/settings"
import { Route as EditorProjectIdRouteImport } from "./routes/editor.$projectId"

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const NotFoundRoute = NotFoundRouteImport.update({
  id: "/not-found",
  path: "/not-found",
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => rootRouteImport,
} as any)
const EditorProjectIdRoute = EditorProjectIdRouteImport.update({
  id: "/editor/$projectId",
  path: "/editor/$projectId",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/not-found": typeof NotFoundRoute
  "/settings": typeof SettingsRoute
  "/editor/$projectId": typeof EditorProjectIdRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/not-found": typeof NotFoundRoute
  "/settings": typeof SettingsRoute
  "/editor/$projectId": typeof EditorProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/not-found": typeof NotFoundRoute
  "/settings": typeof SettingsRoute
  "/editor/$projectId": typeof EditorProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: "/" | "/not-found" | "/settings" | "/editor/$projectId"
  fileRoutesByTo: FileRoutesByTo
  to: "/" | "/not-found" | "/settings" | "/editor/$projectId"
  id: "__root__" | "/" | "/not-found" | "/settings" | "/editor/$projectId"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NotFoundRoute: typeof NotFoundRoute
  SettingsRoute: typeof SettingsRoute
  EditorProjectIdRoute: typeof EditorProjectIdRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/not-found": {
      id: "/not-found"
      path: "/not-found"
      fullPath: "/not-found"
      preLoaderRoute: typeof NotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/settings": {
      id: "/settings"
      path: "/settings"
      fullPath: "/settings"
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/editor/$projectId": {
      id: "/editor/$projectId"
      path: "/editor/$projectId"
      fullPath: "/editor/$projectId"
      preLoaderRoute: typeof EditorProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NotFoundRoute: NotFoundRoute,
  SettingsRoute: SettingsRoute,
  EditorProjectIdRoute: EditorProjectIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
